from __future__ import annotations

from typing import Protocol

from app.models.motor_models import MotorStatus


class MotorControllerInterface(Protocol):
    def start(self) -> None: ...

    def connect(self) -> None: ...

    def close(self) -> None: ...

    def status(self) -> MotorStatus: ...

    def engage(self) -> MotorStatus: ...

    def disengage(self) -> MotorStatus: ...

    def set_origin(self) -> MotorStatus: ...

    def move_to_angle(self, angle_deg: float) -> MotorStatus: ...

    def move_relative(self, delta_deg: float) -> MotorStatus: ...

    def return_origin(self) -> MotorStatus: ...

    def stop(self) -> MotorStatus: ...

    def emergency_stop(self) -> MotorStatus: ...
